apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dag-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      storage-class: dagpath
