apiVersion: v1
kind: PersistentVolume
metadata:
  name: dag-pv
  labels:
    storage-class: dagpath
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/airflow/dags
