apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mvn-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      storage-class: mvnpath
