apiVersion: v1
kind: DeploymentConfig
metadata:
  name: celery
spec:
  replicas: 1
  selector:
    app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - name: celery
        image: apache/airflow:2.5.3rc2-python3.7
        command: ["celery", "-A", "airflow.executors.celery_executor", "worker", "-Q", "default", "--loglevel=info", "--concurrency=2"]
        env:
        - name: AIRFLOW__CELERY__BROKER_URL
          value: redis://redis:6379/0
        - name: AIRFLOW__CELERY__RESULT_BACKEND
          value: redis://redis:6379/0
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        - name: AIRFLOW__CORE__EXECUTOR
          value: CeleryExecutor
        - name: AIRFLOW__CORE__FERNET_KEY
          value: "iFCzUgPTLB1TNb9Zq4ZXxnBlHVaCGFLv55BtlTOjnfw="
        volumeMounts:
        - name: airflow-dags
          mountPath: /opt/airflow/dags
        resources:
          requests:
            memory: "256Mi"
            cpu: "256m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: airflow-dags
        persistentVolumeClaim:
          claimName: dag-pvc
      restartPolicy: Always
