apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-pv
  labels:
    storage-class: storagepath
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/airflow/data
