apiVersion: v1
kind: DeploymentConfig
metadata:
  name: airflow-scheduler
spec:
  replicas: 1
  selector:
    app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      serviceAccountName: airflow-ca
      containers:
      - name: airflow-scheduler
        image: apache/airflow:2.5.3rc2-python3.7
        command: ["airflow", "scheduler"]
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: CeleryExecutor
        - name: AIRFLOW__CELERY__BROKER_URL
          value: redis://redis:6379/0
        - name: AIRFLOW__CELERY__RESULT_BACKEND
          value: redis://redis:6379/0
        - name: AIRFLOW__CELERY__WORKER_LOG_SERVER_PORT
          value: "8793"
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          value: "<SECRET_KEY>"
        - name: AIRFLOW__CORE__FERNET_KEY
          value: "<SECRET_KEY>"
        - name: AIRFLOW__CORE__LOAD_EXAMPLES
          value: "false"
        - name: AIRFLOW__WEBSERVER__RBAC
          value: "true"
        volumeMounts:
        - name: airflow-dags
          mountPath: /opt/airflow/dags
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      volumes:
      - name: airflow-dags
        persistentVolumeClaim:
          claimName: dag-pvc
      restartPolicy: Always
