apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    storage-class: hostpath
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/postgres
