apiVersion: v1
kind: DeploymentConfig
metadata:
  name: redis
spec:
  replicas: 1
  selector:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0.1
        ports:
        - containerPort: 6379
